### ISSUE TITLE
Exceptions

### ISSUE THREAD

**Issue by wizcheu** [herilalaina/mosaic_ml#1]
1. Many classifiers doesn't have the function `set_params` (such as `DecisionTree`, `LibLinear_SVC`, `LibSVM_SVC`, `RandomForest`) so it raises many exceptions: `AttributeError: 'DecisionTree' object has no attribute 'set_params'` and so on
2. Exception log:
```
Traceback (most recent call last):
  File "/data/mosaic_ml/examples/simple_example.py", line 21, in <module>
    res = autoML.fit(X_train, y_train, X_test, y_test, categorical_features=cat)
  File "/data/mosaic_ml/mosaic_ml/automl.py", line 154, in fit
    raise(e)
  File "/data/mosaic_ml/mosaic_ml/automl.py", line 152, in fit
    nb_simulation=100000000000, intial_configuration=intial_configurations)
  File "/data/mosaic_ml/mosaic_ml/mosaic_wrapper/mosaic.py", line 61, in run
    self.mcts.run(nb_simulation, intial_configuration, generate_image_path)
  File "/data/mosaic_ml/mosaic_ml/mosaic_wrapper/mcts.py", line 162, in run
    self.MCT_SEARCH()
  File "/data/mosaic_ml/mosaic_ml/mosaic_wrapper/mcts.py", line 56, in MCT_SEARCH
    reward = self.PLAYOUT(front)
  File "/data/mosaic_ml/mosaic_ml/mosaic_wrapper/mcts.py", line 105, in PLAYOUT
    playout_nodes = self.env.rollout_in_expert_neighborhood(self.tree.get_path_to_node(node_id))
  File "/data/mosaic_ml/mosaic_ml/sklearn_env.py", line 181, in rollout_in_expert_neighborhood
    raise(e)
  File "/data/mosaic_ml/mosaic_ml/sklearn_env.py", line 173, in rollout_in_expert_neighborhood
    for c in get_one_exchange_neighbourhood_with_history(expert, self.seed, history):
  File "/opt/conda/envs/ML/lib/python3.7/site-packages/mosaic-0.1b0-py3.7.egg/mosaic/external/ConfigSpace/util.py", line 174, in get_one_exchange_neighbourhood_with_history
  File "ConfigSpace/configuration_space.pyx", line 1345, in ConfigSpace.configuration_space.Configuration.__init__
TypeError: Configuration expects an instance of <class 'ConfigSpace.configuration_space.ConfigurationSpace'>, you provided '<class 'mosaic.external.ConfigSpace.configuration_space.ConfigurationSpace'>'
```

**Comment by wizcheu** [comment]
One more code error: you have changed the function name `get_childs()` in MOSAIC node.py to `get_children()` but in MOSAIC_ML mcts.py you haven't.

**Comment by wizcheu** [comment]
And so many abstract functions in MOSAIC parent class env.py are not implemented in sklearn_env.py(such as `get_nb_children`)
Log:
```
Traceback (most recent call last):
  File "/data/mosaic_ml/examples/simple_example.py", line 21, in <module>
    res = autoML.fit(X_train, y_train, X_test, y_test, categorical_features=cat)
  File "/data/mosaic_ml/mosaic_ml/automl.py", line 154, in fit
    raise(e)
  File "/data/mosaic_ml/mosaic_ml/automl.py", line 152, in fit
    nb_simulation=100000000000, intial_configuration=intial_configurations)
  File "/data/mosaic_ml/mosaic_ml/mosaic_wrapper/mosaic.py", line 61, in run
    self.mcts.run(nb_simulation, intial_configuration, generate_image_path)
  File "/data/mosaic_ml/mosaic_ml/mosaic_wrapper/mcts.py", line 162, in run
    self.MCT_SEARCH()
  File "/data/mosaic_ml/mosaic_ml/mosaic_wrapper/mcts.py", line 55, in MCT_SEARCH
    front = self.TREEPOLICY()
  File "/data/mosaic_ml/mosaic_ml/mosaic_wrapper/mcts.py", line 75, in TREEPOLICY
    if not self.tree.fully_expanded(node, self.env):
  File "/opt/conda/envs/ML/lib/python3.7/site-packages/mosaic-0.1b0-py3.7.egg/mosaic/node.py", line 50, in fully_expanded
  File "/opt/conda/envs/ML/lib/python3.7/site-packages/mosaic-0.1b0-py3.7.egg/mosaic/env.py", line 57, in get_nb_children
```

**Comment by wizcheu** [comment]
```
Traceback (most recent call last):
  File "/data/mosaic_ml/examples/simple_example.py", line 21, in <module>
    res = autoML.fit(X_train, y_train, X_test, y_test, categorical_features=cat)
  File "/data/mosaic_ml/mosaic_ml/automl.py", line 154, in fit
    raise(e)
  File "/data/mosaic_ml/mosaic_ml/automl.py", line 152, in fit
    nb_simulation=100000000000, intial_configuration=intial_configurations)
  File "/data/mosaic_ml/mosaic_ml/mosaic_wrapper/mosaic.py", line 62, in run
    return self.mcts.bestconfig, self.mcts.bestscore
AttributeError: 'MCTS' object has no attribute 'bestconfig'
```
May I wander if you have a normal code that can reproduce your paper...

**Comment by herilalaina** [comment]
Thank you for the feedback ! These issues are now fixed in master.  The actual version generates scores for only the vanilla setting. The ensemble and metalearning branch will be merge to the master soon.
