### ISSUE TITLE
TypeError: not all arguments converted during string formatting

### ISSUE THREAD

**Issue by ZilinXiang** [herilalaina/mosaic_ml#2]
I reinstall the package as your suggestions in `Readme.md`. There are many logging errors, I show one of them.
```--- Logging error ---
Traceback (most recent call last):
  File "/home/zilin/anaconda3/envs/autoCPDP/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/home/zilin/anaconda3/envs/autoCPDP/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/home/zilin/anaconda3/envs/autoCPDP/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/home/zilin/anaconda3/envs/autoCPDP/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "simple_example.py", line 16, in <module>
    best_config, best_score = autoML.fit(X_train, y_train, X_test, y_test, categorical_features=cat)
  File "/home/zilin/anaconda3/envs/autoCPDP/lib/python3.6/site-packages/mosaic_ml/automl.py", line 179, in fit
    nb_simulation=100000000000, initial_configurations=initial_configurations)
  File "/home/zilin/anaconda3/envs/autoCPDP/lib/python3.6/site-packages/mosaic/mosaic.py", line 82, in run
    self.mcts.run(nb_simulation, initial_configurations, nb_iter_to_generate_img)
  File "/home/zilin/anaconda3/envs/autoCPDP/lib/python3.6/site-packages/mosaic_ml/mosaic_wrapper/mcts.py", line 67, in run
    res, config = self.MCT_SEARCH()
  File "/home/zilin/anaconda3/envs/autoCPDP/lib/python3.6/site-packages/mosaic_ml/mosaic_wrapper/mcts.py", line 25, in MCT_SEARCH
    reward, config = super().MCT_SEARCH()
  File "/home/zilin/anaconda3/envs/autoCPDP/lib/python3.6/site-packages/mosaic/mcts.py", line 68, in MCT_SEARCH
    front = self.TREEPOLICY()
  File "/home/zilin/anaconda3/envs/autoCPDP/lib/python3.6/site-packages/mosaic/mcts.py", line 106, in TREEPOLICY
    state=self.tree.get_path_to_node(node))
  File "/home/zilin/anaconda3/envs/autoCPDP/lib/python3.6/site-packages/mosaic/strategy/policy.py", line 41, in selection
    self.logger.info("vals", vals)
Message: 'vals'
Arguments: ([0.3822858955115988],)
````
And a key error,
```
Traceback (most recent call last):
  File "simple_example.py", line 16, in <module>
    best_config, best_score = autoML.fit(X_train, y_train, X_test, y_test, categorical_features=cat)
  File "/home/zilin/anaconda3/envs/autoCPDP/lib/python3.6/site-packages/mosaic_ml/automl.py", line 181, in fit
    raise (e)
  File "/home/zilin/anaconda3/envs/autoCPDP/lib/python3.6/site-packages/mosaic_ml/automl.py", line 179, in fit
    nb_simulation=100000000000, initial_configurations=initial_configurations)
  File "/home/zilin/anaconda3/envs/autoCPDP/lib/python3.6/site-packages/mosaic/mosaic.py", line 82, in run
    self.mcts.run(nb_simulation, initial_configurations, nb_iter_to_generate_img)
  File "/home/zilin/anaconda3/envs/autoCPDP/lib/python3.6/site-packages/mosaic_ml/mosaic_wrapper/mcts.py", line 67, in run
    res, config = self.MCT_SEARCH()
  File "/home/zilin/anaconda3/envs/autoCPDP/lib/python3.6/site-packages/mosaic_ml/mosaic_wrapper/mcts.py", line 25, in MCT_SEARCH
    reward, config = super().MCT_SEARCH()
  File "/home/zilin/anaconda3/envs/autoCPDP/lib/python3.6/site-packages/mosaic/mcts.py", line 68, in MCT_SEARCH
    front = self.TREEPOLICY()
  File "/home/zilin/anaconda3/envs/autoCPDP/lib/python3.6/site-packages/mosaic/mcts.py", line 106, in TREEPOLICY
    state=self.tree.get_path_to_node(node))
  File "/home/zilin/anaconda3/envs/autoCPDP/lib/python3.6/site-packages/mosaic/strategy/policy.py", line 44, in selection
    self.logger.info("c=", self.policy_arg["c"])
KeyError: 'c'

```

**Comment by herilalaina** [comment]
Hi!
Did you try to reinstall mosaic from v0-alpha branch ?

> pip uninstall mosaic
> pip uninstall mosaic_ml
> pip install git+https://github.com/herilalaina/mosaic@v0-alpha
> pip install git+https://github.com/herilalaina/mosaic_ml

**Comment by ZilinXiang** [comment]
Okay, I fix the problem as your suggestion. Thanks!
